AWSTemplateFormatVersion: 2010-09-09
Description: "Sample Lambda Functions using AWS Cloud Formation"

Parameters:
  LambdaSrcS3Bucket:
    Description: "The S3 Bucket of our Lambda code."
    Type: String
    Default: "jcj-aws-my-bucket"
  LambdaSrcS3Key:
    Description: "The S3 object Key of our Lambda code."
    Type: String
    Default: "lambda_src/hello_lambda.zip"

Resources: 
  cfnMyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Sample CFN Lambda Function"
      FunctionName: cfnMyLambdaFunction
      Role: arn:aws:iam::971422705459:role/S3FileCreateNotifierRole
      Handler: hello_lambda.lambda_handler
      Runtime: python3.12
      Code:
        S3Bucket: !Ref LambdaSrcS3Bucket
        S3Key: !Ref LambdaSrcS3Key