AWSTemplateFormatVersion: 2010-09-09
Description: "Sample S3 bucket using cloud formation"
#Metadata: 

Parameters: 
  bucketName:
    Description: "S3 Bucket Name"
    Type: String
    Default: "jcj-aws-my-cfn-bucket"

#Mappings: 

#Conditions: 

Resources: 
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref bucketName
      Tags:
        - Key:  AppName
          Value: AWSTRN
#Outputs: